/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.searchai.controller; import cn.zhuatech.searchai.common.ApiResponse; import cn.zhuatech.searchai.service.EnterpriseSearchService; import jakarta.validation.Valid; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*; /**
                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                           */
@RestController @RequestMapping("/api/ai") @PreAuthorize("hasAnyRole('DOMAIN_USER','DOMAIN_OPERATOR','ADMIN')") public class AiFeatureController { private final EnterpriseSearchService service; /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             */
public AiFeatureController(EnterpriseSearchService service){this.service=service;} /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                */
@PostMapping("/search/plan") public ApiResponse<EnterpriseSearchService.Result> execute(@Valid @RequestBody EnterpriseSearchService.Request request){return ApiResponse.ok("权限感知搜索计划完成",service.plan(request));} }